### PR TITLE
Adding dataset for new chimera frontend

### PR DESCRIPTION
**Pull request by Ronan-Hix**
Adds new datasets for use with the answer testing of the new Chimera frontend.

### CODE REVIEW

**Comment by yt-fido** [comment]
Can one of the admins verify this patch?

**Comment by Xarthisius** [comment]
I'm also looking at the sizes of those datasets and they're quite big. Would it be possible to find something smaller for tests?

**Comment by Ronan-Hix** [comment]
Hey,

I was told to curl the data using `curl -T [datafile name].tar.gz http://use.yt/upload/`, if it should be uploaded to a different location, I can do that. As for data size, the F37 dataset could be decreased to <300MB without any issue. The C15 dataset is comprised of 45 "wedges" that combine to make up the simulation grid at a given timestep. One of the tests for the frontend checks that these wedges are meshed together correctly on read-in. I could decrease the size of the dataset by only including a few of the 45 wedges, so long as that wouldn't be considered to undermine the rigor of the test.

**Comment by Xarthisius** [comment]
> I was told to curl the data using `curl -T [datafile name].tar.gz http://use.yt/upload/`

That's fine, but you haven't shared the urls that `use.yt/upload/` returned

**Comment by Ronan-Hix** [comment]
Sorry, I'm new to the process. What steps should I take to share those urls? Apologies if there's a standard process for getting data moved from `use.yt/upload/` to `yt-project/data` that I'm unaware of.

**Comment by Xarthisius** [comment]
> Sorry, I'm new to the process. What steps should I take to share those urls? Apologies if there's a standard process for getting data moved from `use.yt/upload/` to `yt-project/data` that I'm unaware of.

When you upload data to `use.yt/upload` it returns the url that other people can use to download the data, e.g.:

```
xarth@shakuras /tmp $ echo "hello" > test.txt
xarth@shakuras /tmp $ curl -T test.txt http://use.yt/upload/
Stream body handler: received 6 bytes
http://use.yt/upload/392c289b
xarth@shakuras /tmp $ rm -rf test.txt && curl -JO http://use.yt/upload/392c289b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0    122      0 --:--:-- --:--:-- --:--:--   122
curl: Saved to filename 'test.txt'
xarth@shakuras /tmp $ cat test.txt
hello
```

See that `http://use.yt/upload/392c289b` ? That's what you share. Do you still have those urls?

**Comment by Xarthisius** [comment]
I looked into database and identified them by size. FTR:

```
$ curl -JO http://use.yt/upload/ab645a18
curl: Saved to filename 'F37_80.tar.gz'
$ curl -JO http://use.yt/upload/f9c85197
curl: Saved to filename 'C15-3D-3deg.tar.gz'
```

**Review by Xarthisius — APPROVED** [review]

**Comment by Ronan-Hix** [comment]
Those are indeed the urls that curl passed out, I had just pulled them back up. Many thanks!

**Pull request merged**
