### PR TITLE
DOC: fix urls to YTEP domain

### LINKED ISSUE #119: ytep link on main webpage is broken
### Bug report

**Bug summary**

the ytep link 404s

**Code for reproduction**

1. Go to: https://yt-project.org/
2. Hover over "quick links" at the top, and select "YTEPs"

the page is not found.

I don't remember where the webpages live.

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

### PR DESCRIPTION
**Pull request by neutrinoceros**
goal: fix #119
the link to YTEP 1776 (governance) is still broken, and I don't know where to find that page now

### CODE REVIEW

**Comment by neutrinoceros** [comment]
ping @zingale if you have any lead for the governance page

**Comment by zingale** [comment]
interestingly it is not on `master`, but it is found here: `https://github.com/yt-project/ytep/tree/jcoughlin11/master/source/YTEPs`

**Comment by neutrinoceros** [comment]
Nice ! `git bisect` -> https://github.com/yt-project/ytep/commit/8e0fc89ee53a78dde21d1679f4332856e96be2bc
So the file was just renamed.

**Comment by neutrinoceros** [comment]
fixed it. Now we have the same problem as with https://github.com/yt-project/yt/pull/4407#discussion_r1161136743, it'd be nice if we could avoid linking the "master" branch explicitly, but AFAICT this is now ready for review

**Pull request merged**
