### PR TITLE
Add special relativistic GAMER simulation

### PR DESCRIPTION
**Pull request by jzuhone**
This adds a special relativistic simulation for the GAMER frontend. The file is already in the correct location on the server. 

This is to support https://github.com/yt-project/yt/pull/3033.

### CODE REVIEW

**Comment by matthewturk** [comment]
@jzuhone I'm getting 403 forbidden for `https://yt-project.org/data/JetICMWall.tar.gz` .

**Comment by jzuhone** [comment]
@matthewturk sorry, permissions not set properly

**Comment by jzuhone** [comment]
@Xarthisius can you put this dataset on the Jenkins box?

**Comment by Xarthisius** [comment]
> @Xarthisius can you put this dataset on the Jenkins box?

Done.

**Pull request merged**
