### PR TITLE
Add magneticum dataset

### PR DESCRIPTION
**Pull request by jzuhone**
This is a Gadget dataset from the Magneticum simulations (http://www.magneticum.org). Supporting code from yt to follow.

### CODE REVIEW

**Review by matthewturk — APPROVED** [review]

**Comment by neutrinoceros** [comment]
Such PR usually contain a link to a tarball. Where's the actual data ?

**Comment by jzuhone** [comment]
@neutrinoceros I don't understand what you're getting at. The data is placed on the dickenson server which runs the website and the link is in the commit.

**Comment by neutrinoceros** [comment]
Oh so it's already available there ? Sorry that wasn't clear to me.
My remark about the corresponding json file on the main repo still stands though

**Comment by jzuhone** [comment]
@neutrinoceros I placed the data there just before I submitted the PR.

**Review by Xarthisius — APPROVED** [review]

**Pull request merged**
