### PR TITLE
Add KeplerianRing

### PR DESCRIPTION
**Pull request by ngoldbaum**
@JBorrow could you verify that the metadata and description are ok here? I'm pretty sure the "code" entry is wrong at least.

Following the pattern we use for the other data files in our test suite, the tarball I've uploaded extracts to the following directory structure:

```
[nathang@dxl1 yt_data]$ ls KeplerianRing/
keplerian_ring_test_data.hdf5
```

### CODE REVIEW

**Comment by JBorrow** [comment]
This looks good, but as you say the code description is slightly wrong. This data has been processed through the SWIFT code (https://gitlab.cosma.dur.ac.uk/swift/swiftsim) but the output files are designed to be GADGET compatible. Perhaps put "SWIFT (GADGET)"?

**Comment by ngoldbaum** [comment]
Cool, hadn't heard of Swift before now.

**Comment by JBorrow** [comment]
That's fair -- not many people have (yet)! It's still in a pretty early phase but essentially we plan for it to be a (faster) drop-in replacement for GADGET that's considerably easier to add subgrid physics to.

**Comment by ngoldbaum** [comment]
How does the description look now?

**Comment by JBorrow** [comment]
Looks perfect to me. Thanks!

**Pull request merged**
