### PR TITLE
Entry for magneticum_camels file

### PR DESCRIPTION
**Pull request by jzuhone**
This PR adds an entry for a new Gadget dataset from the CAMELS suite of simulations, in support of PR https://github.com/yt-project/yt/pull/4584

### CODE REVIEW

**Comment by yt-fido** [comment]
Can one of the admins verify this patch?

**Comment by jzuhone** [comment]
Someone other than me!

**Comment by jzuhone** [comment]
Someone want to bump this?

**Review by neutrinoceros — APPROVED** [review]
I'm happy to approve, but I don't have permission to actually install the files on the server.

**Comment by jzuhone** [comment]
I've already placed the file on the server.

**Pull request merged**
