### PR TITLE
add news tab and news item for yt development workshop 

### PR DESCRIPTION
**Pull request by munkm**
This is an initial stab at adding a news dropdown for the yt project page. I didn't do anything fancy like a feed, but this should allow us to select stories from a news dropdown. I'm happy to revise if you have any feedback about the content. I still need to:

- [ ] verify that the news dropdown link works
- [ ] add all issues and PRs to this post

let me know if there's any content you'd like added

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Just want to double-check - did you know there is a [yt project blog](https://blog.yt-project.org/)? It hasn't been used in a while but my first impression is that this sort of content probably belongs there.

Now that said, it wouldn't be crazy to e.g. move the blog content over here or just abandon the blog in favor of a news page, the blog is basically abandoned at this point.

**Comment by munkm** [comment]
I did know about the blog (and that it hasn't been updated in a while). I started writing this because I thought it'd be good to put the workshop summary in a visible place. Now that I'm thinking about it though, I could also move this post to the blog and switch the "news" dropdown to a link to the blog if that'd be better?

**Comment by ngoldbaum** [comment]
Yeah, I think having a link to the blog at the top level would be a good idea. Right now it's buried in the "quick links" dropdown.

**Comment by munkm** [comment]
Oh wow. I hadn't noticed that! 😬

**Comment by matthewturk** [comment]
:crying_cat_face: Looks like our window has closed on this one!

**Comment by matthewturk** [comment]
We will re-do this when we find a place for this content!

**Pull request closed without merging**
